name: Testing Haystack-Readme integration

on:
  push:
    branches:
      - sync-nodes-doc-test

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Github Action
        uses: readmeio/rdme@7.2.0
        with:
          rdme: docs ./docs --key="${{ secrets.FAKEAPI }}" --version=1.0
